# A container that runs elasticsearch. The upstream image has a volume defined,
# so indexes persist.
es:
  build: ./es
  ports:
    - "8000:8000"

# A Data Volume Container to persist any code you might care to index. On a
# Linux host, you can squirrel away code in the shared "dxr" source checkout,
# but, on a Mac, /code will be more attractive because it offers better IO
# performance than VirtualBox's shared folder implementation.
code:
  build: ./code

# A Data Volume Container so we don't lose our whole virtualenv and need to
# re-download all the Python packages every time the dev image is rebuilt
venv:
  build: ./venv

# An interactive container for experimentation and debugging
dev:
  build: ./dev
  net: container:es
  ports:
    - "8000:8000"
  volumes:
    # XXX: Workaround for ro file system and directory of /home/dxr/dxr when mounting it
    # If the original ":Z" flag is really necessary, set it in command line.
    # Or, it will leave to blank so the issue won't happen.
    - ../..:/home/dxr/dxr$Z
    - $SOURCE:/home/dxr/source
    - $CONFIG:/home/dxr/dxr.config
  volumes_from:
    - code
    - venv
